// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpBwVet4npoeyh5k_3a8lQOXEcq8Hkbi4',
    appId: '1:326872340451:web:1de757605d0854c7c2f2d6',
    messagingSenderId: '326872340451',
    projectId: 'asroostore-fe079',
    authDomain: 'asroostore-fe079.firebaseapp.com',
    storageBucket: 'asroostore-fe079.firebasestorage.app',
    measurementId: 'G-H63D2RQNR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHLvb812v7H0ZQ_L7X3kS5PfRhTzqtQ8M',
    appId: '1:326872340451:android:389a8b0dd5705685c2f2d6',
    messagingSenderId: '326872340451',
    projectId: 'asroostore-fe079',
    storageBucket: 'asroostore-fe079.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8b2We8aXFjb9dRQ8I_0uFrUxl6z1HtXA',
    appId: '1:326872340451:ios:45bb24b415d99eb0c2f2d6',
    messagingSenderId: '326872340451',
    projectId: 'asroostore-fe079',
    storageBucket: 'asroostore-fe079.firebasestorage.app',
    iosBundleId: 'com.example.asrooStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8b2We8aXFjb9dRQ8I_0uFrUxl6z1HtXA',
    appId: '1:326872340451:ios:45bb24b415d99eb0c2f2d6',
    messagingSenderId: '326872340451',
    projectId: 'asroostore-fe079',
    storageBucket: 'asroostore-fe079.firebasestorage.app',
    iosBundleId: 'com.example.asrooStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpBwVet4npoeyh5k_3a8lQOXEcq8Hkbi4',
    appId: '1:326872340451:web:3d273c0c1d25fb35c2f2d6',
    messagingSenderId: '326872340451',
    projectId: 'asroostore-fe079',
    authDomain: 'asroostore-fe079.firebaseapp.com',
    storageBucket: 'asroostore-fe079.firebasestorage.app',
    measurementId: 'G-KJJFWGDWDG',
  );
}
